// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODO.Repository;

#nullable disable

namespace TODO.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TODO.Models.Todo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreationTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DueDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bdff234c-33d3-447f-80ee-84e43a33f01d",
                            Content = "draw 12345 awaiting draw result",
                            CreationTime = 1542111235544L,
                            DueDate = 1622374526379L,
                            Status = "Active",
                            Title = "MegaMillions awaiting Draw Result",
                            Type = "Results"
                        },
                        new
                        {
                            Id = "ec65203f-4c74-4ac1-9b4b-579e5c40b09b",
                            Content = "draw 23232 awaiting draw result",
                            CreationTime = 1622374526379L,
                            DueDate = 1622374714232L,
                            Status = "Active",
                            Title = "EuroJackpot awaiting Draw Result",
                            Type = "Results"
                        },
                        new
                        {
                            Id = "f234f5cb-6ec0-4475-bb32-b6ebf9ab42ad",
                            Content = "draw 56345 awaiting draw result",
                            CreationTime = 1622374714232L,
                            DueDate = 1622375111971L,
                            Status = "Done",
                            Title = "Powerball awaiting Draw Result",
                            Type = "Results"
                        },
                        new
                        {
                            Id = "6f4c1ba5-7927-478b-bf43-48af79af56d8",
                            Content = "draw 23232 awaiting draw result",
                            CreationTime = 1622375111971L,
                            DueDate = 1622375125381L,
                            Status = "Active",
                            Title = "EuroJackpot awaiting Draw Result",
                            Type = "Results"
                        },
                        new
                        {
                            Id = "bdff234c-33d3-447f-80ee-84e43a33f014",
                            Content = "user 34332 awaiting 15$ payout",
                            CreationTime = 1542111235544L,
                            DueDate = 1622374526340L,
                            Status = "Done",
                            Title = "User awaiting win payout",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = "ec65203f-4c74-4ac1-9b4b-572e5c40b03b",
                            Content = "user 32566 awaiting 10.30$ payout",
                            CreationTime = 1622374526379L,
                            DueDate = 1622374714232L,
                            Status = "Active",
                            Title = "User awaiting win payout",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = "ec65203f-4c74-4ac1-9b4b-572e2c40b03b",
                            Content = "user 234787 awaiting 1000.40$ payout",
                            CreationTime = 1622374526379L,
                            DueDate = 1622374714232L,
                            Status = "Active",
                            Title = "User awaiting win payout",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = "bdff234c-33d3-447f-80ee-84e43a23f01d",
                            Content = "withdraw id 5452 awaiting approval",
                            CreationTime = 1542111235544L,
                            DueDate = 1622539315287L,
                            Status = "Active",
                            Title = "User Withdraw pending",
                            Type = "Withdraw"
                        },
                        new
                        {
                            Id = "ec65203f-42374-4ac1-9b4b-579e5c40b09b",
                            Content = "withdraw id 23443 awaiting approval",
                            CreationTime = 1622374526379L,
                            DueDate = 1622539324959L,
                            Status = "Active",
                            Title = "User Withdraw pending",
                            Type = "Withdraw"
                        },
                        new
                        {
                            Id = "f234f5cb-6ec0-4475-aa32-b6ebf9ab42ad",
                            Content = "withdraw id 127888 awaiting approval",
                            CreationTime = 1622374714232L,
                            DueDate = 1622539336894L,
                            Status = "Done",
                            Title = "User Withdraw pending",
                            Type = "Withdraw"
                        },
                        new
                        {
                            Id = "124f703e-cdcb-11eb-b8bc-0242ac130003",
                            Content = "draw 897644 awaiting draw result",
                            CreationTime = 1622375111971L,
                            DueDate = 1622539347152L,
                            Status = "Active",
                            Title = "Super enaloto awaiting Draw Result",
                            Type = "Results"
                        },
                        new
                        {
                            Id = "0d3e9c82-cdcb-11eb-b8bc-0242ac130003",
                            Content = "user 45422 awaiting 15$ payout",
                            CreationTime = 1542111235544L,
                            DueDate = 1622539355849L,
                            Status = "Done",
                            Title = "User awaiting win payout",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = "08c37970-cdcb-11eb-b8bc-0242ac130003",
                            Content = "user 32566 awaiting 10.30$ payout",
                            CreationTime = 1622374526379L,
                            DueDate = 1622539365375L,
                            Status = "Active",
                            Title = "User awaiting win payout",
                            Type = "Wins"
                        },
                        new
                        {
                            Id = "ffd17a42-cdca-11eb-b8bc-0242ac130003",
                            Content = "user 675553 awaiting 1000.40$ payout",
                            CreationTime = 1622374526379L,
                            DueDate = 1622539372100L,
                            Status = "Active",
                            Title = "User awaiting win payout",
                            Type = "Wins"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
